# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ing.life
email: ing.marcosp@icloud.com
author: Marcos P.
twitter_username: ing_marcosp            
github_username: ingmarcosp


description: > #pass
  El objetivo es plasmar vivencias como desarrollador, administrador, usuario. Participativo, abierto a opiniones y comentarios. Servir de carta de presentación, un nexo entre las redes sociales pero que brinda nuevo contenido útil para el día a día y todo tipo de usuarios.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ingmarcosp.github.io" # the base hostname & protocol for your site
permalink: /post/:title

# Build settings
markdown: kramdown
theme: minima

#destination: blog
include: [images, favicon.ico]